import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { Breadcrumbs } from "@/components/BreadCrumbs";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className="min-h-screen flex flex-col rtl">
        <Header />
        <div className="pt-16">
          <Breadcrumbs />
        </div>
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
