import { defineType, defineField } from "sanity";

export default defineType({
  name: "post",
  title: "Blog Post",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "seo", title: "SEO" },
    { name: "relations", title: "Relations" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Post Title",
      type: "string",
      group: "content",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug (URL)",
      type: "slug",
      group: "content",
      options: { source: "title" },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "mainImage",
      title: "Main Image",
      type: "image",
      group: "content",
      options: { hotspot: true },
    }),
    defineField({
      name: "body",
      title: "Content",
      type: "array",
      group: "content",
      of: [{ type: "block" }, { type: "image" }],
    }),
    defineField({
      name: "categories",
      title: "Categories",
      type: "array",
      group: "relations",
      of: [{ type: "reference", to: { type: "category" } }],
    }),
    defineField({
      name: "relatedPosts",
      title: "Related Posts",
      type: "array",
      group: "relations",
      of: [{ type: "reference", to: { type: "post" } }],
    }),
    defineField({
      name: "relatedServices",
      title: "Related Services",
      description:
        "Service slugs this post relates to (used to surface the post on service landing pages). Example: سباكة, تنظيف, صيانة, تنسيق-حدائق, مقاولات, نقل-عفش, عزل.",
      type: "array",
      group: "relations",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "relatedCity",
      title: "Related City",
      description:
        "City slug if this post is specifically about a city. Example: riyadh, jeddah, dammam.",
      type: "string",
      group: "relations",
    }),
    defineField({ name: "authorName", title: "Author Name", type: "string", group: "content" }),
    defineField({ name: "authorRole", title: "Author Role", type: "string", group: "content" }),
    defineField({ name: "publishedAt", title: "Published At", type: "date", group: "content" }),
    defineField({ name: "readTime", title: "Read Time (min)", type: "number", group: "content" }),
    defineField({
      name: "excerpt",
      title: "Short Description",
      type: "text",
      group: "content",
      rows: 3,
    }),
    defineField({
      name: "seoTitle",
      title: "SEO Title",
      description:
        "Optional. Overrides the post title in the <title> tag and OG/Twitter. Useful for longer keyword-rich titles.",
      type: "string",
      group: "seo",
    }),
    defineField({
      name: "metaDescription",
      title: "SEO Meta Description",
      type: "text",
      group: "seo",
      rows: 2,
    }),
    defineField({
      name: "ogImage",
      title: "Social Share Image (OG)",
      description: "Optional. Falls back to Main Image. Recommended 1200×630.",
      type: "image",
      group: "seo",
      options: { hotspot: true },
    }),
    defineField({
      name: "keywords",
      title: "Keywords",
      type: "array",
      group: "seo",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
  ],
});
