import { defineField, defineType } from "sanity";

export default defineType({
  name: "postIdea",
  title: "Post Idea (Editorial Backlog)",
  type: "document",
  groups: [
    { name: "core", title: "Core", default: true },
    { name: "seo", title: "SEO Planning" },
    { name: "outline", title: "Outline" },
    { name: "tracking", title: "Performance Tracking" },
  ],
  fields: [
    defineField({
      name: "workingTitle",
      title: "Working Title",
      description: "Draft title — final post title may differ.",
      type: "string",
      group: "core",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      group: "core",
      options: {
        list: [
          { title: "Idea", value: "idea" },
          { title: "Briefed", value: "briefed" },
          { title: "Drafting", value: "drafting" },
          { title: "QA", value: "qa" },
          { title: "Published", value: "published" },
          { title: "Archived", value: "archived" },
        ],
        layout: "radio",
      },
      initialValue: "idea",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "priority",
      title: "Priority",
      type: "string",
      group: "core",
      options: {
        list: [
          { title: "High (write this week)", value: "high" },
          { title: "Medium (this month)", value: "medium" },
          { title: "Low (backlog)", value: "low" },
        ],
        layout: "radio",
      },
      initialValue: "medium",
    }),
    defineField({
      name: "linkedPost",
      title: "Linked Post",
      description: "Reference the post once it's drafted/published.",
      type: "reference",
      group: "core",
      to: [{ type: "post" }],
    }),
    defineField({
      name: "notes",
      title: "Notes",
      description: "Free-form notes — research findings, source quotes, decisions.",
      type: "text",
      group: "core",
      rows: 4,
    }),
    defineField({
      name: "primaryKeyword",
      title: "Primary Target Keyword",
      type: "string",
      group: "seo",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "secondaryKeywords",
      title: "Secondary Keywords",
      type: "array",
      group: "seo",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "searchIntent",
      title: "Search Intent",
      type: "string",
      group: "seo",
      options: {
        list: [
          { title: "Informational (how/what/why)", value: "informational" },
          { title: "Commercial (compare/research before buying)", value: "commercial" },
          { title: "Transactional (buy/hire now)", value: "transactional" },
          { title: "Navigational (find a specific brand)", value: "navigational" },
        ],
        layout: "radio",
      },
      initialValue: "informational",
    }),
    defineField({
      name: "articleType",
      title: "Article Type",
      description: "Drives the schema.org type emitted in the post JSON-LD.",
      type: "string",
      group: "seo",
      options: {
        list: [
          { title: "Article (regular post)", value: "Article" },
          { title: "HowTo (step-by-step)", value: "HowTo" },
          { title: "Guide", value: "Guide" },
          { title: "Comparison (X vs Y)", value: "Comparison" },
          { title: "Listicle (Top N)", value: "Listicle" },
        ],
        layout: "radio",
      },
      initialValue: "Article",
    }),
    defineField({
      name: "targetWordCount",
      title: "Target Word Count",
      description: "Body word count target. Recommended: 1800-2200 for KSA Arabic SEO.",
      type: "number",
      group: "seo",
      initialValue: 2000,
    }),
    defineField({
      name: "targetService",
      title: "Target Service",
      description: "Which service slug this post supports. Used to populate the post's relatedServices later.",
      type: "string",
      group: "seo",
      options: {
        list: [
          { title: "سباكة", value: "سباكة" },
          { title: "تنظيف", value: "تنظيف" },
          { title: "صيانة", value: "صيانة" },
          { title: "تنسيق-حدائق", value: "تنسيق-حدائق" },
          { title: "مقاولات", value: "مقاولات" },
          { title: "نقل-عفش", value: "نقل-عفش" },
          { title: "عزل", value: "عزل" },
        ],
      },
    }),
    defineField({
      name: "targetCity",
      title: "Target City (optional)",
      description: "City slug if post is geo-specific. Leave empty for evergreen posts.",
      type: "string",
      group: "seo",
      options: {
        list: [
          { title: "Riyadh / الرياض", value: "riyadh" },
          { title: "Jeddah / جدة", value: "jeddah" },
          { title: "Dammam / الدمام", value: "dammam" },
          { title: "Mecca / مكة", value: "mecca" },
          { title: "Medina / المدينة", value: "medina" },
          { title: "Taif / الطائف", value: "taif" },
          { title: "Abha / أبها", value: "abha" },
          { title: "Tabuk / تبوك", value: "tabuk" },
          { title: "Buraydah / بريدة", value: "buraydah" },
          { title: "Khamis Mushait / خميس مشيط", value: "khamis-mushait" },
        ],
      },
    }),
    defineField({
      name: "featuredAnswerDraft",
      title: "Featured Answer Draft (40-60 words)",
      description: "The post's snippet bait — 40-60 word concise answer to the primary query.",
      type: "text",
      group: "outline",
      rows: 4,
    }),
    defineField({
      name: "plannedH2s",
      title: "Planned H2 Sections",
      description: "Outline of body H2 sections in order.",
      type: "array",
      group: "outline",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "plannedFaqs",
      title: "Planned FAQ Questions",
      description: "Just the questions for now — answers get fleshed out in the post.",
      type: "array",
      group: "outline",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "plannedInternalLinks",
      title: "Planned Internal Service Links",
      description: "Slugs of service pages this post should link to. Example: شركة-سباكة, سباك-الرياض.",
      type: "array",
      group: "outline",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "competitorRefs",
      title: "Competitor URLs for Reference",
      description: "URLs of competitor posts ranking for the primary keyword.",
      type: "array",
      group: "outline",
      of: [{ type: "url" }],
    }),
    defineField({
      name: "gscImpressions",
      title: "GSC Impressions (last 28 days)",
      description: "Update monthly from Search Console.",
      type: "number",
      group: "tracking",
    }),
    defineField({
      name: "gscClicks",
      title: "GSC Clicks (last 28 days)",
      type: "number",
      group: "tracking",
    }),
    defineField({
      name: "gscAvgPosition",
      title: "GSC Avg Position",
      type: "number",
      group: "tracking",
    }),
    defineField({
      name: "lastTrackedAt",
      title: "Last Tracked At",
      type: "date",
      group: "tracking",
    }),
  ],
  preview: {
    select: {
      title: "workingTitle",
      status: "status",
      priority: "priority",
      service: "targetService",
    },
    prepare: ({ title, status, priority, service }) => ({
      title,
      subtitle: `[${status}] ${priority || "-"} ${service ? "· " + service : ""}`,
    }),
  },
});
